theme = "cyan_light"

[editor]
mouse = true
scrolloff = 5
auto-completion = true
completion-trigger-len = 2
bufferline = "never"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "position-percentage", "position"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[keys.normal]
";" = "command_mode"
