set nocp
set encoding=utf-8

call plug#begin()
Plug 'altercation/vim-colors-solarized'
call plug#end()

let mapleader = " " " leader key is space
"----------------------------------------------------------------------------------------------------------

" 2. File compatibility and configuration issues
    " Do not keep a backup or .swp file. I don't like to have junk files, my source is anyway in cvs/svn/p4/git.
    set nobackup
    set nowritebackup
    set noswapfile
    set nocompatible " Use Vim defaults (much better!), Vi is for 70's programmers!
    set ts=4 " tabstop - how many columns should the cursor move for one tab
    set sw=4 " shiftwidth - how many columns should the text be indented
    set expandtab " always expands tab to spaces. It is good when peers use different editor.
    set wrap " wraps longs lines to screen size

"----------------------------------------------------------------------------------------------------------

" 3. Color, Look&Feel Configuration

    set guifont=Consolas:h12
    " set guifont=Cascadia_Code:h11
    syntax enable
    " set background=light

    if has('gui_running')
        set background=light
    else
        set background=dark
    endif   
    colorscheme solarized
    " Use different color schemes for different set of files.
    " au BufEnter *.* colorscheme zellner
    " au BufEnter *.log colorscheme desert
    " au BufEnter *.build colorscheme darkbone
    " au BufEnter *.txt colorscheme darkbone

    " Customize Status line color of current window & non-current windows
    " highlight StatusLineNC guifg=SlateBlue guibg=Yellow
    " highlight StatusLine guifg=Gray guibg=White

    set noerrorbells visualbell t_vb=
    autocmd GUIEnter * set visualbell t_vb=  
    set vb t_vb= " stop beeping or flashing the screen
    set wildmenu
    set wildoptions=pum

"----------------------------------------------------------------------------------------------------------

" 4. Display specific (screen resolution dependent settings. Adjust these if your screen resolution will be too less or you have bigger monitor)
    set laststatus=2 " Show the status line even if only one file is being edited
    " Make command line two lines high
    set ch=1

"----------------------------------------------------------------------------------------------------------

" 5. Working with split windows and tabs
    " 5.1 Working with tabs
    "~~~~~~~~~~~~~~~~~~~~~~~
    if version >= 700
        " always enable Vim tabs
        set showtabline=2
        " set tab features just like browser
        " open tab, close tab, next tab, previous tab (just like Chrome and Firefox keyboard shortcuts)
      map <C-t> <Esc>:tabnew<CR>
      map <C-F4> <Esc>:tabclose<CR>
      map <C-Tab> <Esc>:tabnext<CR>
      map <C-S-Tab> <Esc>:tabprev<CR>
    endif

    " 5.2 Working with windows 
    "~~~~~~~~~~~~~~~~~~~~~~~
    " Switch between splits very fast (for multi-file editing) by maximizing target split - http://vim.wikia.com/wiki/VimTip173
    map <C-J> <C-W>j<C-W>_
    map <C-K> <C-W>k<C-W>_
    map <C-H> <C-W>h<C-W>|
    map <C-L> <C-W>l<C-W>|
    map <C-=> <C-W>=

"----------------------------------------------------------------------------------------------------------

" 6. General file editing
    " 6.1 Common Settings to enable better editing
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        set bs=2 " allow backspacing over everything in insert mode
        set ai " always set autoindenting on

        set showmatch " show matching brackets
        syntax on " Switch on syntax highlighting.
        set hidden " This option allows you to switch between multiple buffers without saving a changed buffer
        set hlsearch " Switch on search pattern highlighting.
        " set mousehide " Hide the mouse pointer while typing.

        
        " Easy pasting to windows apps - http://vim.wikia.com/wiki/VimTip21
        " yank always copies to unnamed register, so it is available in windows clipboard for other applications.
        set clipboard=unnamed

        "Set the history size to maximum. by default it is 20 - http://vim.wikia.com/wiki/VimTip45
        set history=80

        "Plugins config - http://vim.sourceforge.net/script.php?script_id=448
        :filetype plugin on 
        
        " Always change the directory to working directory of file in current buffer - http://vim.wikia.com/wiki/VimTip64
        autocmd BufEnter * call CHANGE_CURR_DIR()

        " See Help documentation by entering command :help 'sessionoptions'
        set sessionoptions+=resize
        set sessionoptions+=winpos
        set sessionoptions+=folds
        set sessionoptions+=tabpages

        set hlsearch " highlights the previously searched string
        set incsearch " higlight search string as search pattern is entered
        :hi Search ctermfg=red ctermbg=gray
        set suffixes+=.class,.exe,.obj,.dat,.dll " Show these file types at the end while using :edit command

        " Configuration for explorer.vim to open the new file by doing vertical split and opening it in right window.
        " For more info use command :help file-explorer
        let g:explVertical=1	" Split vertically
        let g:explSplitRight=1  " Put new window right of the explorer window
        let c_comment_strings=1 " I like highlighting strings inside C comments

        " Buffer Explorer - http://vim.sourceforge.net/scripts/script.php?script_id=159
        let g:miniBufExplMapWindowNavVim = 1 
        let g:miniBufExplMapWindowNavArrows = 1 
        let g:miniBufExplMapCTabSwitchBuffs = 1

    " 6.2 Common shortcuts
    "~~~~~~~~~~~~~~~~~~~~~~~
        
        " yank to system clipboard
        map <space-y> :"+y<CR>
        
        " paste from the system clipboard
        map <leader>pp :"+gP<CR>

        " open netrw
        map <leader>pv :Ex<CR>

         " Netrw customization
        let g:netrw_liststyle=1
        let g:netrw_banner=0

        " Don't use Ex mode, use Q for formatting
        map Q gq

        " save the current file
        map <F2> :w!<CR>
        map <C-S> :w<CR>

        " go to next file in the open file list.
        map <F3> :n<CR>
        
        " go to previous file in the open file list.
        map <S-F3> :previous<CR>

        " Show the list of all functions in current file - http://vim.wikia.com/wiki/VimTip79
        nmap <F4> :call ShowFunc()<CR>

        " Reload the current file
        map <F5> :e!<CR>
        map <M-r> :e!<CR>

        " split the current file (horizontal split)
        map <F6> :split<CR>

        " Shift F6 will do vertical split
        map <S-F6> : vsplit<CR>

        " to execute Ant build tool.
        map <F7> :!ant<CR>

        " Quit without saving
        map <C-Q> :q!<CR>

        " Quit after saving
        map <C-X> :x<CR>

        " Comment-ify the visually selected block using C style comments
        vmap \/* omxomy<ESC>`xO/*<ESC>`yo*/<ESC>

        "Copy current filename with path to clipboard
        map     <F8> :let @* = expand('%:p')<cr>
        map!    <F8> <Esc>:let @* = expand('%:p')<cr>

        " WOK: CTRL-SPACE: keyword completion, Just like Eclipse :)
        map  <C-space> <C-n>
        map! <C-space> <C-n>
        map  <C-S-space> <C-p>
        map! <C-S-space> <C-p>

        " Folding shortcuts
        map - v%zf
        map = v%zd

    " 6.3 Setup for quick jump to sections of file
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        " Tag settings - http://vim.wikia.com/wiki/VimTip94
        " Vim will search for the file named 'tags', starting with the current directory and then going to the parent directory and then 
        " recursively to the directory one level above, till it either locates the 'tags' file or reaches the root '/' directory. 
        set tags=tags;/
        set tagstack

        " For "gf" to open a file  where complete path is available in current file. (useful in C/C++ programming to open *.h files).
        " "**" matches a subtree, up to 100 directories deep.  Example:
        ":set path=/home/user_x/src/**
        " means search in the whole subtree under "/home/usr_x/src".
        :set path=.,./**

        " To jump between the '=' and ';' in an assignment using <S-%>. Useful for languages like C/C++ and Java.
        :au FileType c,cpp,java set mps+==:;
        " Including '<' and '>' (HTML): >
        :set mps+=<:>

        " Bookmark feature in Vim - http://vim.wikia.com/wiki/VimTip42
        " To save all book marks in 100 files.It will save local marks (a-z) by default. The '100 tells Vim to save marks and other information for up to 100 files. The f1 directive tells Vim to also save global marks (A-Z) when it exits. If you don't want Vim to do this, set it to f0 instead.
        " :marks give all marks
        " ma  - book mark "a"
        " `a  - go to bookmark "a"
        set viminfo='100,f1

"----------------------------------------------------------------------------------------------------------

" 7. Programming language specific 

" 7.1 Generic Programming Language setup
  "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    augroup prog
    au!
        " When starting to edit a file:
        " For *.c, *.cpp, *.java and *.h files set formatting of comments and set C-indenting on.
        " For other files switch it off.
        " Don't change the order, it's important that the line with * comes first.
        autocmd BufNewFile,BufRead,BufReadPost *       set formatoptions=tcql nocindent comments&
        autocmd BufNewFile,BufRead,BufReadPost *.c,*.h,*.cpp,*.java set formatoptions=croql cindent comments=sr:/*,mb:*,el:*/,://
        autocmd BufNewFile,BufRead *.fun,*.pks,*.pkb,*.sql,*.pls,*.plsql    setf plsql
    augroup END
" 7.2 Java shortcuts
  "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    augroup jprog
    au!
        abbr Sysl/ System.out.println(
        abbr Sys/ System.out.print(
        abbr Syse/ System.exit(1);
        abbr mark/ //TODO: Shambu
        abbr todo/ //TODO: Gopi<NL><BS>
        abbr op out.println("
        abbr main/ public static void main(String[] args) throws Exception {<NL><BS>
        abbr dbg/ Debug\.println(2,"");<NL><BS>
        abbr trace/ catch (Exception e) {<NL><Tab>e.printStackTrace();<NL><BS><BS><BS><BS>}<NL><BS>
        abbr impx/ import org.xml.sax.*;<NL>import org.xml.sax.helpers.*;<NL><BS>
        abbr msgbox/ MessageBox.Show("text", "caption", MessageBoxButtons.OK, MessageBoxIcon.Error);

        " When starting to .java a file, set formatting of comments and set C-indenting on.
        " For other files switch it off.
        " Don't change the order, it's important that the line with * comes first.
        autocmd BufRead *       set formatoptions=tcql nocindent comments&
        autocmd BufRead *.java, set formatoptions=croql cindent comments=sr:/*,mb:*,el:*/,://
    augroup END

" 7.3 C/C++ shortcuts
  "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  " Note : to work on C/C++ Windows, download windows version of cscope from http://iamphet.nm.ru/cscope/index.html
  
  " (logging macros)
    augroup cprog
    au!
        abbr log0/ LOG_ENTER(L"");
        abbr log1/ LOG_EXIT(L"");
        abbr logi/ LOG_INFO(L"");
        "cs add s:\btbuild\scripts\cscope.out
        let g:buildFile = 'default.build' 
        let g:antOption = '-verbose' 
    augroup END

" 7.4 HTML shortcuts
  "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    augroup html
        " bold
        vmap \b y:s/\<<c-r>"\>/<b>&<\/b>/g<CR>
        " bold - global
        vmap \B y:%s/\<<c-r>"\>/<b>&<\/b>/g<CR>
        " italics
        vmap \i y:s/\<<c-r>"\>/<i>&<\/i>/g<CR>
        " italics - global
        vmap \I y:%s/\<<c-r>"\>/<i>&<\/i>/g<CR>
        " fixed width font
        vmap \tt y:s/\<<c-r>"\>/<tt>&<\/tt>/g<CR>
        " fixed width font - global
        vmap \TT y:%s/\<<c-r>"\>/<tt>&<\/tt>/g<CR>
    augroup END

"----------------------------------------------------------------------------------------------------------

" 8 Custom inline scripts
    " 8.1 Show the list of all functions in current file - http://vim.wikia.com/wiki/VimTip79
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    function! ShowFunc()
        
        let gf_s = &grepformat
        let gp_s = &grepprg
        
        let &grepformat = '%*\k%*\sfunction%*\s%l%*\s%f %*\s%m'
        let &grepprg = 'ctags -x --c++-types=f --sort=no -o -'
        " for java. TODO: update it to handle all .java, .c, .cpp
        "let &grepprg = 'ctags -x --java-types=cfimp --sort=no -o -'

        write
        silent! grep %
        cwindow

        "let &grepformat = gf_s
        let &grepprg = gp_s
    endfunc

    "8.2 Always change the directory to working directory of file in current buffer - http://vim.wikia.com/wiki/VimTip64
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    function! CHANGE_CURR_DIR()
        let _dir = expand("%:p:h")
        exec "cd " . _dir
        unlet _dir
    endfunction

"----------------------------------------------------------------------------------------------------------

" 9 Custom Vim Setup to create new files/download other files.
    " 9.1 Default copyright header
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            " Whenever I create a new class in Java /C# , I want copyright header :).  Disable this if you don't want.
            au BufNewFile *.cs 0r $VIM/Header.cs
            au BufNewFile *.java 0r $VIM/Header.java

    " 9.2 Vim scripts - Install and uncomment below lines. By default these scripts are not part of Vim distribution.
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        " 9.2.1 Tags menu for various programming language source files 
            " http://www.vim.org/scripts/script.php?script_id=215
            "source $VIM/xtra-vim-scripts/FuncMenu.vim
        " 9.3 FTP Plugins
            "source $VIM/xtra-vim-scripts/intellisense.vim
            "source $VIM/xtra-vim-scripts/ftplugin/cs_vis.vim
            "source $VIM/xtra-vim-scripts/ftplugin/java_vis.vim
            "source $VIM/xtra-vim-scripts/ftplugin/html_vis.vim
        " 9.4 Jad Plugin - When .class file is opened with Vim, decompile it using jad.exe and show the source code.
        " Downlaod jad from http://www.varaneckas.com/jad and make sure jad " executable is in your system path. 
            "source $VIM/xtra-vim-scripts\jad.vim
